### ISSUE TITLE
i-tab-bar和i-modal有冲突?

### ISSUE THREAD

**Issue by swearl** [TalkingData/iview-weapp#132]
i-tab-bar和i-modal一起使用,
tabbar的图标选中颜色丢失

**Comment by sorcer0123** [comment]
我也发现了 不光这个 还有跟grid-item也冲突，你解决了吗？

**Comment by swearl** [comment]
我的临时解决方法是用css
```css
.bar-item-index--i-tab-bar-item-icon.item-index--i-tab-bar-item-icon-current,
.i-tab-bar-item-icon-current {
	color:#2d8cf0;
}
```
