### ISSUE TITLE
Tag里面的红色丢了一个属性

### ISSUE THREAD

**Issue by ourfor** [TalkingData/iview-weapp#339]
https://github.com/TalkingData/iview-weapp/blob/a874b7edf568809ef74e78b7c547ac961d727207/dist/tag/index.wxss#L1
```css
.i-tag-red {
	background: #ed3f14;
	color: #fff;
  border-color: #ed3f14
}
```
