### ISSUE TITLE
i-grid-label的i-class属性无效

### ISSUE THREAD

**Issue by xianer0405** [TalkingData/iview-weapp#61]
代码如下
`<i-grid-item class="base-grid-item" i-class="grid-item-fix">
    <i-grid-icon>
       <i-icon size="24" type="mail"></i-icon>
    </i-grid-icon>
    <i-grid-label i-class="red-font-fix">邮箱</i-grid-label>
</i-grid-item>`

**Comment by martinx** [comment]
对的，目前代码i-grid-label漏了外部样式i-class，如果不等官方更新的话，可以手工修改 dist/grid-label/index.wxml

```
<view class="i-class i-grid-label"><slot></slot></view>
```

增加一个i-class，然后就可以在你的 wxss 中增加样式了，不过可能因为i-grid-label中增加已经定义了 color 属性，不管我将i-class 放在前面还是后面，都不能生效，只有在 申明！important 时才有效果。

```css
.color_red {
  color: red !important;
}

.color_blue {
  color: blue !important;
}

.color_green {
  color: green !important;
}
```

![image](https://user-images.githubusercontent.com/6499/41949567-8ee93946-79f4-11e8-9f64-46b6820d2e9f.png)


不知道是否有其他办法不需要！important的。
