### ISSUE TITLE
i-card组件thumb属性指定的图片如何自定义成圆角模式

### ISSUE THREAD

**Issue by xianer0405** [TalkingData/iview-weapp#62]

**Comment by martinx** [comment]
用你常规的样式即可，如：

```xml
<i-card title="卡片标题" extra="额外内容" thumb="https://i.loli.net/2017/08/21/599a521472424.jpg"  i-class="card-demo">
    <view slot="content">内容不错</view>
    <view slot="footer">尾部内容</view>
</i-card>
```

```css
.card-demo image {
  border-radius: 50%;
}
```
